import { JAVASCRIPT_AREA_ID, TYPESCRIPT_AREA_ID } from './areas'
import type { Battle, Enemy } from './types'

const enemy = (
  id: string,
  name: string,
  role: Enemy['role'],
  visualId: string,
  hp: number,
  attackName: string,
  attackDamage: number,
  glyph: string,
): Enemy => ({ id, name, role, visualId, hp, maxHp: hp, attackName, attackDamage, glyph })

export const battles: Battle[] = [
  {
    id: 1,
    areaId: JAVASCRIPT_AREA_ID,
    label: 'JS-01 · LIVE INCIDENT',
    title: '最初のtarget異常',
    subtitle: 'まず現場で症状を再現する。全部のcodeを理解できなくてもいい。現在のstateと実際に選ばれるtargetを見て、何を読めるようになる必要があるか掴もう',
    recommendedLevel: 1,
    expReward: 12,
    goldReward: 20,
    enemies: [
      enemy('slime-a', 'Slime', 'standard', 'slime', 34, 'Nibble', 5, '●'),
      enemy('goblin-a', 'Goblin', 'standard', 'goblin', 72, 'Heavy Slash', 8, '▲'),
    ],
    skillIds: ['trace', 'pulse', 'nova'],
    unlockSkillId: 'viper',
  },
  {
    id: 2,
    areaId: JAVASCRIPT_AREA_ID,
    label: 'JS-10 · SECOND SYMPTOM',
    title: '広がるバグ',
    subtitle: '別の戦闘機能まで同じ異常が広がった。Forestで追った条件と影響範囲を使い、複数の処理に共通するtraceを探す',
    recommendedLevel: 3,
    expReward: 80,
    goldReward: 30,
    enemies: [
      enemy('slime-b', 'Slime', 'standard', 'slime', 42, 'Nibble', 6, '●'),
      enemy('goblin-b', 'Goblin', 'standard', 'goblin', 68, 'Heavy Slash', 15, '▲'),
      enemy('golem-b', 'Golem', 'standard', 'golem', 124, 'Stone Fist', 9, '■'),
    ],
    skillIds: ['trace', 'pulse', 'nova', 'viper', 'lock', 'alert'],
    unlockSkillId: 'moon-edge',
  },
  {
    id: 3,
    areaId: JAVASCRIPT_AREA_ID,
    label: 'JS-19 · ROOT CAUSE',
    title: '暴走するCode Core',
    subtitle: '草原からDeep Forestまで追ったtraceがCode Coreへ集約された。ここまで読んだcodeとstateを使い、JavaScript地方のroot causeを止める',
    recommendedLevel: 5,
    expReward: 100,
    goldReward: 50,
    isBoss: true,
    enemies: [
      enemy('slime-c', 'Slime', 'standard', 'slime', 46, 'Bite', 3, '●'),
      enemy('goblin-c', 'Goblin', 'standard', 'goblin', 84, 'Execution', 8, '▲'),
      enemy('boss-c', 'Boss', 'boss', 'boss', 156, 'Runtime Cascade', 12, '◆'),
    ],
    skillIds: [
      'trace',
      'pulse',
      'nova',
      'viper',
      'lock',
      'alert',
      'moon-edge',
      'sweep',
      'judge',
    ],
    multiLineSkillIds: ['moon-edge', 'sweep', 'judge'],
  },
  {
    id: 4,
    areaId: TYPESCRIPT_AREA_ID,
    label: 'TS-01 · CONTRACT TRACE',
    title: 'API契約の食い違い',
    subtitle: 'Enemy API更新後からtarget結果がずれている。型注釈が示す保証と、callbackが実際に評価する条件を分けて入口の処理を追う',
    recommendedLevel: 1,
    expReward: 50,
    goldReward: 25,
    enemies: [
      enemy('slime-ts-a', 'Slime', 'standard', 'slime', 46, 'Type Ping', 4, '●'),
      enemy('goblin-ts-a', 'Goblin', 'standard', 'goblin', 72, 'Strict Slash', 8, '▲'),
    ],
    skillIds: ['ts-scan', 'ts-guard', 'ts-label'],
    unlockSkillId: 'ts-union',
  },
  {
    id: 5,
    areaId: TYPESCRIPT_AREA_ID,
    label: 'TS-02 · DATA SHAPE',
    title: '消える設定値',
    subtitle: '同じAPI更新後、unionとoptional propertyを持つ設定値の異常が複数moduleへ波及した。候補の型と現在値を分けて共通contractを探す',
    recommendedLevel: 2,
    expReward: 70,
    goldReward: 35,
    enemies: [
      enemy('slime-ts-b', 'Slime', 'standard', 'slime', 44, 'Undefined Bite', 4, '●'),
      enemy('goblin-ts-b', 'Goblin', 'standard', 'goblin', 74, 'Union Slash', 8, '▲'),
      enemy('golem-ts-b', 'Golem', 'standard', 'golem', 104, 'Object Fist', 10, '■'),
    ],
    skillIds: ['ts-scan', 'ts-guard', 'ts-label', 'ts-union', 'ts-optional'],
    multiLineSkillIds: ['ts-union', 'ts-optional'],
    unlockSkillId: 'ts-narrow',
  },
  {
    id: 6,
    areaId: TYPESCRIPT_AREA_ID,
    label: 'TS-03 · ROOT CAUSE',
    title: '壊れたShared Contract',
    subtitle: '異常は新旧data shapeを解釈する共通contractとFrontier Compilerへ集約されていた。narrowing・generic・keyofを追って根本原因を直す',
    recommendedLevel: 3,
    expReward: 120,
    goldReward: 60,
    isBoss: true,
    enemies: [
      enemy('slime-ts-c', 'Slime', 'standard', 'slime', 46, 'Literal Spark', 3, '●'),
      enemy('goblin-ts-c', 'Goblin', 'standard', 'goblin', 82, 'Narrow Edge', 7, '▲'),
      enemy('boss-ts-c', 'Boss', 'boss', 'boss', 132, 'Compiler Crash', 10, '◆'),
    ],
    skillIds: [
      'ts-scan',
      'ts-guard',
      'ts-label',
      'ts-union',
      'ts-optional',
      'ts-narrow',
      'ts-keyof',
    ],
    multiLineSkillIds: ['ts-union', 'ts-optional', 'ts-narrow', 'ts-keyof'],
  },
  {
    id: 7,
    areaId: JAVASCRIPT_AREA_ID,
    label: 'JS-02 · INCIDENT PREP',
    title: '数字を見比べる',
    subtitle: 'さっきのincidentに出ていたHPの比較だけを取り出す。`.`の右側にある値と、`<` / `>` の向きを一つずつ読んでみよう',
    recommendedLevel: 1,
    expReward: 8,
    goldReward: 0,
    enemies: [
      enemy('sprout-training-a', 'Sprout', 'standard', 'sprout', 30, 'Leaf Tap', 3, '♣'),
      enemy('boar-training-a', 'Boar', 'standard', 'boar', 82, 'Tackle', 5, '♠'),
    ],
    skillIds: ['trace', 'nova'],
  },
  {
    id: 8,
    areaId: JAVASCRIPT_AREA_ID,
    label: 'JS-03 · INCIDENT PREP',
    title: '名前を見比べる',
    subtitle: 'incidentで見たname条件を切り出す。`.name`で名前を見て、`===`が何と同じかを確かめよう',
    recommendedLevel: 1,
    expReward: 8,
    goldReward: 0,
    enemies: [
      enemy('goblin-training-b', 'Goblin', 'standard', 'goblin', 36, 'Wooden Slash', 4, '▲'),
      enemy('golem-training-b', 'Golem', 'standard', 'golem', 82, 'Practice Fist', 5, '■'),
    ],
    skillIds: ['pulse', 'nova', 'trace'],
  },
  {
    id: 9,
    areaId: JAVASCRIPT_AREA_ID,
    label: 'JS-04 · INCIDENT PREP',
    title: '前から最初の一体を探す',
    subtitle: 'incidentのselectorが使っていたfind()を切り出す。`enemies`を前から見て、条件に合った最初の一体で止まる流れを確かめよう',
    recommendedLevel: 1,
    expReward: 8,
    goldReward: 0,
    enemies: [
      enemy('slime-training-c', 'Slime', 'standard', 'slime', 30, 'Practice Bite', 3, '●'),
      enemy('goblin-training-c', 'Goblin', 'standard', 'goblin', 38, 'Wooden Slash', 4, '▲'),
      enemy('golem-training-c', 'Golem', 'standard', 'golem', 84, 'Practice Fist', 5, '■'),
    ],
    skillIds: ['trace', 'pulse', 'nova'],
  },
  {
    id: 10,
    areaId: JAVASCRIPT_AREA_ID,
    label: 'JS-05 · FOREST TRACE',
    title: '二つとも当てはまる相手',
    subtitle: '草原のincidentから続く条件がForestで二つに増えた。`&&`の左右を一つずつ確認し、両方trueになる最初の敵をfind()で追う',
    recommendedLevel: 2,
    expReward: 16,
    goldReward: 6,
    enemies: [
      enemy('goblin-forest-a-low', 'Goblin', 'standard', 'goblin', 42, 'Twig Slash', 4, '▲'),
      enemy('goblin-forest-a-high', 'Goblin', 'standard', 'goblin', 64, 'Branch Slash', 7, '▲'),
      enemy('boar-forest-a', 'Boar', 'standard', 'boar', 86, 'Tackle', 6, '♠'),
    ],
    skillIds: ['trace', 'pulse', 'nova', 'link'],
    unlockSkillId: 'link',
  },
  {
    id: 11,
    areaId: JAVASCRIPT_AREA_ID,
    label: 'JS-06 · FOREST TRACE',
    title: 'どちらか一つでも当てはまる相手',
    subtitle: '`||`は別の入口から同じ異常経路へ入る条件になっている。既習の`&&`と分けて、かっこの内側からtraceを追う',
    recommendedLevel: 2,
    expReward: 20,
    goldReward: 8,
    enemies: [
      enemy('slime-forest-b', 'Slime', 'standard', 'slime', 30, 'Moss Bite', 4, '●'),
      enemy('goblin-forest-b', 'Goblin', 'standard', 'goblin', 58, 'Branch Slash', 7, '▲'),
      enemy('boar-forest-b', 'Boar', 'standard', 'boar', 92, 'Tackle', 6, '♠'),
    ],
    skillIds: ['trace', 'link', 'fork'],
    unlockSkillId: 'fork',
  },
  {
    id: 12,
    areaId: JAVASCRIPT_AREA_ID,
    label: 'JS-07 · TRACE JUNCTION',
    title: '森の分かれ道を読み切る',
    subtitle: '新しい記号は増えない。`&&`と`||`、比較、find()を内側から順番に読み、異常traceがどこへ集まるか確かめよう',
    recommendedLevel: 2,
    expReward: 24,
    goldReward: 10,
    enemies: [
      enemy('slime-forest-c', 'Slime', 'standard', 'slime', 34, 'Moss Bite', 4, '●'),
      enemy('goblin-forest-c', 'Goblin', 'standard', 'goblin', 62, 'Branch Slash', 7, '▲'),
      enemy('boar-forest-c', 'Boar', 'standard', 'boar', 88, 'Tackle', 6, '♠'),
    ],
    skillIds: ['trace', 'pulse', 'nova', 'link', 'fork'],
  },
  {
    id: 13,
    areaId: JAVASCRIPT_AREA_ID,
    label: 'JS-08 · TRACE BLOCKED',
    title: '森を塞ぐ番人',
    subtitle: '新しい記号はない。ここまで追ったcomparison / name / find() / && / ||を使い、incidentの経路を塞ぐForest Guardianを突破する',
    recommendedLevel: 3,
    expReward: 36,
    goldReward: 18,
    enemies: [
      enemy('sprout-forest-midboss', 'Sprout', 'standard', 'sprout', 36, 'Thorn Tap', 5, '♣'),
      enemy('goblin-forest-midboss', 'Goblin', 'standard', 'goblin', 68, 'Bark Slash', 8, '▲'),
      enemy('guardian-forest-midboss', 'Guardian', 'elite', 'guardian', 126, 'Root Crash', 10, '◆'),
    ],
    skillIds: ['trace', 'pulse', 'nova', 'link', 'fork'],
  },
  {
    id: 14,
    areaId: JAVASCRIPT_AREA_ID,
    label: 'JS-09 · IMPACT RANGE',
    title: '影響を受ける相手を全部追う',
    subtitle: '異常が一体だけでなく複数targetへ広がっている。find()とfilter()を比べ、同じ条件で影響範囲がどう変わるか追う',
    recommendedLevel: 3,
    expReward: 28,
    goldReward: 12,
    enemies: [
      enemy('slime-filter-a', 'Slime', 'standard', 'slime', 30, 'Moss Bite', 4, '●'),
      enemy('sprout-filter-a', 'Sprout', 'standard', 'sprout', 36, 'Thorn Tap', 5, '♣'),
      enemy('boar-filter-a', 'Boar', 'standard', 'boar', 88, 'Tackle', 6, '♠'),
    ],
    skillIds: ['trace', 'gather', 'nova'],
    unlockSkillId: 'gather',
  },
  {
    id: 15,
    areaId: JAVASCRIPT_AREA_ID,
    label: 'JS-11 · SHARED TRACE',
    title: '条件が変わっても同じ流れを追う',
    subtitle: '二つ目の症状も同じcall pathへ入った。filter()の条件が反対向きでも、結果へ残る相手を最後まで追って共通traceを確認する',
    recommendedLevel: 3,
    expReward: 30,
    goldReward: 14,
    enemies: [
      enemy('slime-filter-b', 'Slime', 'standard', 'slime', 32, 'Moss Bite', 4, '●'),
      enemy('boar-filter-b', 'Boar', 'standard', 'boar', 74, 'Tackle', 6, '♠'),
      enemy('guardian-filter-b', 'Guardian', 'standard', 'guardian', 96, 'Root Crash', 8, '◆'),
    ],
    skillIds: ['gather', 'echo', 'nova'],
    unlockSkillId: 'echo',
  },
  {
    id: 16,
    areaId: JAVASCRIPT_AREA_ID,
    label: 'JS-12 · TRACE TRANSFORMED',
    title: '同じEnemyが別の形で渡されている',
    subtitle: 'traceの途中でdataの形が変わった。map()でEnemyを別のobjectへ変換し、既習のfind()へ渡る流れを追う',
    recommendedLevel: 3,
    expReward: 32,
    goldReward: 15,
    enemies: [
      enemy('slime-map-a', 'Slime', 'standard', 'slime', 34, 'Moss Bite', 4, '●'),
      enemy('goblin-map-a', 'Goblin', 'standard', 'goblin', 66, 'Branch Slash', 7, '▲'),
      enemy('guardian-map-a', 'Guardian', 'standard', 'guardian', 92, 'Root Crash', 8, '◆'),
    ],
    skillIds: ['project', 'gather', 'echo'],
    unlockSkillId: 'project',
  },
  {
    id: 17,
    areaId: JAVASCRIPT_AREA_ID,
    label: 'JS-13 · REAL-WORLD SIGNAL',
    title: '一体でも異常があるとalarmが立つ',
    subtitle: 'REAL WORLDのalarmとCODE WORLDの状態が連動している。some()が返すtrue / falseを読み、一体でも条件に合うか確かめる',
    recommendedLevel: 3,
    expReward: 34,
    goldReward: 16,
    enemies: [
      enemy('slime-some-a', 'Slime', 'standard', 'slime', 38, 'Moss Bite', 4, '●'),
      enemy('goblin-some-a', 'Goblin', 'standard', 'goblin', 72, 'Branch Slash', 7, '▲'),
      enemy('guardian-some-a', 'Guardian', 'standard', 'guardian', 90, 'Root Crash', 8, '◆'),
    ],
    skillIds: ['project', 'signal', 'gather', 'echo'],
    unlockSkillId: 'signal',
  },
  {
    id: 18,
    areaId: JAVASCRIPT_AREA_ID,
    label: 'JS-14 · BARRIER RULE',
    title: '群れ全体で結界が開閉する',
    subtitle: 'Deep Forestのbarrierは群れ全体のstateで動く。every()が全員を確認する流れをsome()と比べて読む',
    recommendedLevel: 3,
    expReward: 36,
    goldReward: 17,
    enemies: [
      enemy('sprout-every-a', 'Sprout', 'standard', 'sprout', 42, 'Thorn Tap', 5, '♣'),
      enemy('goblin-every-a', 'Goblin', 'standard', 'goblin', 64, 'Branch Slash', 7, '▲'),
      enemy('guardian-every-a', 'Guardian', 'standard', 'guardian', 86, 'Root Crash', 8, '◆'),
    ],
    skillIds: ['project', 'signal', 'sync', 'echo'],
    unlockSkillId: 'sync',
  },
  {
    id: 19,
    areaId: JAVASCRIPT_AREA_ID,
    label: 'JS-15 · ROOT TRACE BLOCKED',
    title: '根を守る第二の番人',
    subtitle: '二つのincident traceが同じ最深部へ集まっている。filter() / map() / some() / every()を読み、junctionを塞ぐRoot Guardianを突破する',
    recommendedLevel: 4,
    expReward: 46,
    goldReward: 22,
    enemies: [
      enemy('sprout-deep-midboss', 'Sprout', 'standard', 'sprout', 44, 'Thorn Tap', 5, '♣'),
      enemy('goblin-deep-midboss', 'Goblin', 'standard', 'goblin', 76, 'Root Slash', 8, '▲'),
      enemy('guardian-deep-midboss', 'Root Guardian', 'elite', 'root-guardian', 128, 'Ancient Root', 11, '◆'),
    ],
    skillIds: ['project', 'signal', 'sync', 'gather', 'echo'],
  },
  {
    id: 20,
    areaId: JAVASCRIPT_AREA_ID,
    label: 'JS-16 · TARGET ORDER',
    title: '候補を並べ替えて先頭を見る',
    subtitle: 'root causeへ入る前にtarget候補の優先順を追う。sort()と[0]を、living → byHp → byHp[0]の中間値へ分けて読む',
    recommendedLevel: 4,
    expReward: 38,
    goldReward: 18,
    enemies: [
      enemy('slime-sort-a', 'Slime', 'standard', 'slime', 36, 'Deep Bite', 5, '●'),
      enemy('goblin-sort-a', 'Goblin', 'standard', 'goblin', 68, 'Root Slash', 8, '▲'),
      enemy('guardian-sort-a', 'Guardian', 'standard', 'guardian', 94, 'Root Crash', 9, '◆'),
    ],
    skillIds: ['order', 'project', 'gather', 'echo'],
    multiLineSkillIds: ['order'],
    unlockSkillId: 'order',
  },
  {
    id: 21,
    areaId: JAVASCRIPT_AREA_ID,
    label: 'JS-17 · MISSING DATA',
    title: '欠けた値がある本番経路を読む',
    subtitle: 'REAL WORLDの一部dataではstatsが欠けている。map()・?.・??・sort()をつなぎ、止まらずにtarget候補へ届く経路を追う',
    recommendedLevel: 4,
    expReward: 40,
    goldReward: 20,
    enemies: [
      enemy('slime-safe-a', 'Slime', 'standard', 'slime', 40, 'Deep Bite', 5, '●'),
      enemy('goblin-safe-a', 'Goblin', 'standard', 'goblin', 72, 'Root Slash', 8, '▲'),
      enemy('guardian-safe-a', 'Guardian', 'standard', 'guardian', 96, 'Root Crash', 9, '◆'),
    ],
    skillIds: ['safe-path', 'order', 'project', 'echo'],
    multiLineSkillIds: ['safe-path', 'order'],
    unlockSkillId: 'safe-path',
  },
  {
    id: 22,
    areaId: JAVASCRIPT_AREA_ID,
    label: 'JS-18 · FINAL TRACE',
    title: '候補が最後に一つへ集約される',
    subtitle: 'Deep Forest最後のtraceで複数候補が一つへ絞られる。reduce()の途中結果bestを順番に追い、その先のCode Coreへつながるruleを確定する',
    recommendedLevel: 4,
    expReward: 44,
    goldReward: 22,
    enemies: [
      enemy('slime-reduce-a', 'Slime', 'standard', 'slime', 44, 'Deep Bite', 5, '●'),
      enemy('goblin-reduce-a', 'Goblin', 'standard', 'goblin', 78, 'Root Slash', 9, '▲'),
      enemy('guardian-reduce-a', 'Guardian', 'standard', 'guardian', 102, 'Root Crash', 12, '◆'),
    ],
    skillIds: ['reduce-focus', 'safe-path', 'order', 'signal', 'sync'],
    multiLineSkillIds: ['reduce-focus', 'safe-path', 'order'],
    unlockSkillId: 'reduce-focus',
  },
]
