import { JAVASCRIPT_AREA_ID, TYPESCRIPT_AREA_ID } from './areas'
import type { Battle, Enemy } from './types'

const enemy = (
  id: string,
  name: string,
  hp: number,
  attackName: string,
  attackDamage: number,
  glyph: string,
): Enemy => ({ id, name, hp, maxHp: hp, attackName, attackDamage, glyph })

export const battles: Battle[] = [
  {
    id: 1,
    areaId: JAVASCRIPT_AREA_ID,
    label: 'CHAPTER 01',
    title: '最初のバグ',
    subtitle: '王国の戦闘システムが違う敵を狙い始めた。新人Code Knightとして、JavaScriptを読みながら壊れたターゲット処理を直そう',
    recommendedLevel: 1,
    expReward: 40,
    goldReward: 20,
    enemies: [
      enemy('slime-a', 'Slime', 34, 'Nibble', 6, '●'),
      enemy('goblin-a', 'Goblin', 72, 'Heavy Slash', 14, '▲'),
    ],
    skillIds: ['trace', 'pulse', 'nova'],
    unlockSkillId: 'viper',
  },
  {
    id: 2,
    areaId: JAVASCRIPT_AREA_ID,
    label: 'CHAPTER 02',
    title: '広がるバグ',
    subtitle: '直したはずなのに、別の戦闘機能までおかしくなった。BYTEとログを追い、複数の処理に共通する壊れたコードを探す',
    recommendedLevel: 2,
    expReward: 80,
    goldReward: 30,
    enemies: [
      enemy('slime-b', 'Slime', 42, 'Nibble', 6, '●'),
      enemy('goblin-b', 'Goblin', 68, 'Heavy Slash', 15, '▲'),
      enemy('golem-b', 'Golem', 124, 'Stone Fist', 9, '■'),
    ],
    skillIds: ['trace', 'pulse', 'nova', 'viper', 'lock', 'alert'],
    unlockSkillId: 'moon-edge',
  },
  {
    id: 3,
    areaId: JAVASCRIPT_AREA_ID,
    label: 'FINAL CHAPTER',
    title: '暴走するCode Core',
    subtitle: 'すべての異常は王国の共通処理を動かすCode Coreにつながっていた。暴走したCoreを止め、JavaScript王国のシステムを復旧せよ',
    recommendedLevel: 3,
    expReward: 100,
    goldReward: 50,
    isBoss: true,
    enemies: [
      enemy('slime-c', 'Slime', 46, 'Bite', 3, '●'),
      enemy('goblin-c', 'Goblin', 84, 'Execution', 8, '▲'),
      enemy('boss-c', 'Boss', 156, 'Runtime Cascade', 12, '◆'),
    ],
    skillIds: [
      'trace',
      'pulse',
      'nova',
      'viper',
      'lock',
      'alert',
      'moon-edge',
      'sweep',
      'judge',
    ],
    multiLineSkillIds: ['moon-edge', 'sweep', 'judge'],
  },
  {
    id: 4,
    areaId: TYPESCRIPT_AREA_ID,
    label: 'CHAPTER 01',
    title: 'API契約の食い違い',
    subtitle: 'Enemy API更新後からtarget結果がずれている。型注釈が示す保証と、callbackが実際に評価する条件を分けて入口の処理を追う',
    recommendedLevel: 1,
    expReward: 50,
    goldReward: 25,
    enemies: [
      enemy('slime-ts-a', 'Slime', 46, 'Type Ping', 4, '●'),
      enemy('goblin-ts-a', 'Goblin', 72, 'Strict Slash', 8, '▲'),
    ],
    skillIds: ['ts-scan', 'ts-guard', 'ts-label'],
    unlockSkillId: 'ts-union',
  },
  {
    id: 5,
    areaId: TYPESCRIPT_AREA_ID,
    label: 'CHAPTER 02',
    title: '消える設定値',
    subtitle: '同じAPI更新後、unionとoptional propertyを持つ設定値の異常が複数moduleへ波及した。候補の型と現在値を分けて共通contractを探す',
    recommendedLevel: 2,
    expReward: 70,
    goldReward: 35,
    enemies: [
      enemy('slime-ts-b', 'Slime', 44, 'Undefined Bite', 4, '●'),
      enemy('goblin-ts-b', 'Goblin', 74, 'Union Slash', 8, '▲'),
      enemy('golem-ts-b', 'Golem', 104, 'Object Fist', 10, '■'),
    ],
    skillIds: ['ts-scan', 'ts-guard', 'ts-label', 'ts-union', 'ts-optional'],
    multiLineSkillIds: ['ts-union', 'ts-optional'],
    unlockSkillId: 'ts-narrow',
  },
  {
    id: 6,
    areaId: TYPESCRIPT_AREA_ID,
    label: 'FINAL CHAPTER',
    title: '壊れたShared Contract',
    subtitle: '異常は新旧data shapeを解釈する共通contractとFrontier Compilerへ集約されていた。narrowing・generic・keyofを追って根本原因を直す',
    recommendedLevel: 3,
    expReward: 120,
    goldReward: 60,
    isBoss: true,
    enemies: [
      enemy('slime-ts-c', 'Slime', 46, 'Literal Spark', 3, '●'),
      enemy('goblin-ts-c', 'Goblin', 82, 'Narrow Edge', 7, '▲'),
      enemy('boss-ts-c', 'Boss', 132, 'Compiler Crash', 10, '◆'),
    ],
    skillIds: [
      'ts-scan',
      'ts-guard',
      'ts-label',
      'ts-union',
      'ts-optional',
      'ts-narrow',
      'ts-keyof',
    ],
    multiLineSkillIds: ['ts-union', 'ts-optional', 'ts-narrow', 'ts-keyof'],
  },
  {
    id: 7,
    areaId: JAVASCRIPT_AREA_ID,
    label: 'VILLAGE TRAINING 01',
    title: '数字を見比べる',
    subtitle: 'まずは敵が持つHPの数字を見る。`.`の右側にある値と、`<` / `>` の向きを一つずつ読んでみよう',
    recommendedLevel: 1,
    expReward: 8,
    goldReward: 0,
    enemies: [
      enemy('sprout-training-a', 'Sprout', 30, 'Leaf Tap', 3, '♣'),
      enemy('boar-training-a', 'Boar', 82, 'Tackle', 5, '♠'),
    ],
    skillIds: ['trace', 'nova'],
  },
  {
    id: 8,
    areaId: JAVASCRIPT_AREA_ID,
    label: 'VILLAGE TRAINING 02',
    title: '名前を見比べる',
    subtitle: '数字だけでなく文字も値として読める。`.name`で名前を見て、`===`が何と同じかを確かめよう',
    recommendedLevel: 1,
    expReward: 8,
    goldReward: 0,
    enemies: [
      enemy('goblin-training-b', 'Goblin', 36, 'Wooden Slash', 4, '▲'),
      enemy('golem-training-b', 'Golem', 82, 'Practice Fist', 5, '■'),
    ],
    skillIds: ['pulse', 'nova', 'trace'],
  },
  {
    id: 9,
    areaId: JAVASCRIPT_AREA_ID,
    label: 'VILLAGE TRAINING 03',
    title: '前から最初の一体を探す',
    subtitle: '`enemies`を前から順に見て、条件に合った最初の一体で止まる。find()の読み方を実戦で確かめよう',
    recommendedLevel: 1,
    expReward: 8,
    goldReward: 0,
    enemies: [
      enemy('slime-training-c', 'Slime', 30, 'Practice Bite', 3, '●'),
      enemy('goblin-training-c', 'Goblin', 38, 'Wooden Slash', 4, '▲'),
      enemy('golem-training-c', 'Golem', 84, 'Practice Fist', 5, '■'),
    ],
    skillIds: ['trace', 'pulse', 'nova'],
  },
  {
    id: 10,
    areaId: JAVASCRIPT_AREA_ID,
    label: 'FOREST LESSON 01',
    title: '二つとも当てはまる相手',
    subtitle: '森では条件が一つ増える。`&&`の左右を一つずつ確認し、両方trueになる最初の敵をfind()で追おう',
    recommendedLevel: 2,
    expReward: 16,
    goldReward: 6,
    enemies: [
      enemy('goblin-forest-a-low', 'Goblin', 42, 'Twig Slash', 4, '▲'),
      enemy('goblin-forest-a-high', 'Goblin', 64, 'Branch Slash', 7, '▲'),
      enemy('boar-forest-a', 'Boar', 86, 'Tackle', 6, '♠'),
    ],
    skillIds: ['trace', 'pulse', 'link'],
    unlockSkillId: 'link',
  },
  {
    id: 11,
    areaId: JAVASCRIPT_AREA_ID,
    label: 'FOREST LESSON 02',
    title: 'どちらか一つでも当てはまる相手',
    subtitle: '`||`は二つの道のどちらかが通ればtrue。既習の`&&`と分けて、かっこの内側から条件を追おう',
    recommendedLevel: 2,
    expReward: 20,
    goldReward: 8,
    enemies: [
      enemy('slime-forest-b', 'Slime', 30, 'Moss Bite', 4, '●'),
      enemy('goblin-forest-b', 'Goblin', 58, 'Branch Slash', 7, '▲'),
      enemy('boar-forest-b', 'Boar', 92, 'Tackle', 6, '♠'),
    ],
    skillIds: ['trace', 'link', 'fork'],
    unlockSkillId: 'fork',
  },
  {
    id: 12,
    areaId: JAVASCRIPT_AREA_ID,
    label: 'FOREST LESSON 03',
    title: '森の分かれ道を読み切る',
    subtitle: '新しい記号は増えない。`&&`と`||`、比較、find()を内側から順番に読み、今の敵の並びへ当てはめよう',
    recommendedLevel: 2,
    expReward: 24,
    goldReward: 10,
    enemies: [
      enemy('slime-forest-c', 'Slime', 34, 'Moss Bite', 4, '●'),
      enemy('goblin-forest-c', 'Goblin', 62, 'Branch Slash', 7, '▲'),
      enemy('boar-forest-c', 'Boar', 88, 'Tackle', 6, '♠'),
    ],
    skillIds: ['trace', 'pulse', 'nova', 'link', 'fork'],
  },
  {
    id: 13,
    areaId: JAVASCRIPT_AREA_ID,
    label: 'FOREST MID-BOSS',
    title: '森を塞ぐ番人',
    subtitle: '新しい記号はない。comparison / name / find() / && / ||を一つずつ読み、Forest Guardianの群れを突破しよう',
    recommendedLevel: 3,
    expReward: 36,
    goldReward: 18,
    enemies: [
      enemy('sprout-forest-midboss', 'Sprout', 36, 'Thorn Tap', 5, '♣'),
      enemy('goblin-forest-midboss', 'Goblin', 68, 'Bark Slash', 8, '▲'),
      enemy('guardian-forest-midboss', 'Guardian', 126, 'Root Crash', 10, '◆'),
    ],
    skillIds: ['trace', 'pulse', 'nova', 'link', 'fork'],
  },
  {
    id: 14,
    areaId: JAVASCRIPT_AREA_ID,
    label: 'FOREST LESSON 04',
    title: '条件に合う相手を全部集める',
    subtitle: 'find()は最初の一体で止まる。filter()は最後まで見て、条件に合う相手を全部集める。同じ条件で違いを比べよう',
    recommendedLevel: 3,
    expReward: 28,
    goldReward: 12,
    enemies: [
      enemy('slime-filter-a', 'Slime', 30, 'Moss Bite', 4, '●'),
      enemy('sprout-filter-a', 'Sprout', 36, 'Thorn Tap', 5, '♣'),
      enemy('boar-filter-a', 'Boar', 88, 'Tackle', 6, '♠'),
    ],
    skillIds: ['trace', 'gather', 'nova'],
    unlockSkillId: 'gather',
  },
  {
    id: 15,
    areaId: JAVASCRIPT_AREA_ID,
    label: 'DEEP FOREST LESSON 01',
    title: '条件の向きが変わっても全部集める',
    subtitle: 'filter()の意味はそのまま。今度は`>`を読み、HPが65より大きい相手を最後まで見て全部集めよう',
    recommendedLevel: 3,
    expReward: 30,
    goldReward: 14,
    enemies: [
      enemy('boar-deep-filter', 'Boar', 92, 'Root Tackle', 7, '♠'),
      enemy('slime-deep-filter', 'Slime', 34, 'Moss Bite', 4, '●'),
      enemy('golem-deep-filter', 'Golem', 78, 'Stone Root', 8, '■'),
    ],
    skillIds: ['gather', 'echo', 'trace'],
    unlockSkillId: 'echo',
  },
]
