import { JAVASCRIPT_AREA_ID, TYPESCRIPT_AREA_ID } from './areas'
import type { Battle, Enemy } from './types'

const enemy = (
  id: string,
  name: string,
  hp: number,
  attackName: string,
  attackDamage: number,
  glyph: string,
): Enemy => ({ id, name, hp, maxHp: hp, attackName, attackDamage, glyph })

export const battles: Battle[] = [
  {
    id: 1,
    areaId: JAVASCRIPT_AREA_ID,
    label: 'BATTLE 01',
    title: 'First Read',
    subtitle: 'コードが選ぶ「対象」を読む',
    recommendedLevel: 1,
    expReward: 40,
    enemies: [
      enemy('slime-a', 'Slime', 34, 'Nibble', 6, '●'),
      enemy('goblin-a', 'Goblin', 72, 'Heavy Slash', 14, '▲'),
    ],
    skillIds: ['trace', 'pulse', 'nova'],
    unlockSkillId: 'viper',
  },
  {
    id: 2,
    areaId: JAVASCRIPT_AREA_ID,
    label: 'BATTLE 02',
    title: 'One or Many',
    subtitle: 'find / filter と複数条件を戦況で使い分ける',
    recommendedLevel: 2,
    expReward: 60,
    enemies: [
      enemy('slime-b', 'Slime', 42, 'Nibble', 6, '●'),
      enemy('goblin-b', 'Goblin', 68, 'Heavy Slash', 15, '▲'),
      enemy('golem-b', 'Golem', 124, 'Stone Fist', 9, '■'),
    ],
    skillIds: ['trace', 'pulse', 'nova', 'viper', 'lock', 'alert'],
    unlockSkillId: 'moon-edge',
  },
  {
    id: 3,
    areaId: JAVASCRIPT_AREA_ID,
    label: 'BATTLE 03',
    title: 'Priority Queue',
    subtitle: '条件・集約・優先順位を読み、倒す順番を決める',
    recommendedLevel: 3,
    expReward: 100,
    isBoss: true,
    enemies: [
      enemy('slime-c', 'Slime', 46, 'Bite', 3, '●'),
      enemy('goblin-c', 'Goblin', 84, 'Execution', 8, '▲'),
      enemy('boss-c', 'Boss', 156, 'Meteor', 12, '◆'),
    ],
    skillIds: [
      'trace',
      'pulse',
      'nova',
      'viper',
      'lock',
      'alert',
      'moon-edge',
      'sweep',
      'judge',
    ],
    multiLineSkillIds: ['moon-edge', 'sweep', 'judge'],
  },
  {
    id: 4,
    areaId: TYPESCRIPT_AREA_ID,
    label: 'BATTLE 04',
    title: 'Typed Entry',
    subtitle: '型注釈を読み、値を調べる条件そのものは変わらないと見抜く',
    recommendedLevel: 1,
    expReward: 50,
    enemies: [
      enemy('slime-ts-a', 'Slime', 46, 'Type Ping', 4, '●'),
      enemy('goblin-ts-a', 'Goblin', 72, 'Strict Slash', 8, '▲'),
    ],
    skillIds: ['ts-scan', 'ts-guard', 'ts-label'],
    unlockSkillId: 'ts-union',
  },
  {
    id: 5,
    areaId: TYPESCRIPT_AREA_ID,
    label: 'BATTLE 05',
    title: 'Maybe Value',
    subtitle: 'unionとoptional propertyを追い、narrowing後の条件を読む',
    recommendedLevel: 2,
    expReward: 70,
    enemies: [
      enemy('slime-ts-b', 'Slime', 44, 'Undefined Bite', 4, '●'),
      enemy('goblin-ts-b', 'Goblin', 74, 'Union Slash', 8, '▲'),
      enemy('golem-ts-b', 'Golem', 104, 'Object Fist', 10, '■'),
    ],
    skillIds: ['ts-scan', 'ts-guard', 'ts-label', 'ts-union', 'ts-optional'],
    multiLineSkillIds: ['ts-union', 'ts-optional'],
    unlockSkillId: 'ts-narrow',
  },
  {
    id: 6,
    areaId: TYPESCRIPT_AREA_ID,
    label: 'BATTLE 06',
    title: 'Frontier Compiler',
    subtitle: '型の絞り込みとproperty keyを複合コードで追う',
    recommendedLevel: 3,
    expReward: 120,
    isBoss: true,
    enemies: [
      enemy('slime-ts-c', 'Slime', 46, 'Literal Spark', 3, '●'),
      enemy('goblin-ts-c', 'Goblin', 82, 'Narrow Edge', 7, '▲'),
      enemy('boss-ts-c', 'Boss', 132, 'Compiler Crash', 10, '◆'),
    ],
    skillIds: [
      'ts-scan',
      'ts-guard',
      'ts-label',
      'ts-union',
      'ts-optional',
      'ts-narrow',
      'ts-keyof',
    ],
    multiLineSkillIds: ['ts-union', 'ts-optional', 'ts-narrow', 'ts-keyof'],
  },
]
