import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { AppRouter } from './AppRouter'
import { AudioUnlock } from './audio/AudioUnlock'
import './styles.css'
import './opening.css'
import './layout-fixes.css'
import './reward.css'
import './dialogue.css'
import './motion.css'
import './audio.css'
import './world.css'
import './overworld-arrival.css'
import './world-motion.css'
import './world-map-transition.css'
import './world-encounter-cue.css'
import './greenfield-village.css'
import './greenfield-village-entry-layout.css'
import './village-exit-label.css'
import './typescript-frontier.css'
import './world-portal-scenes.css'
import './greenfield-village-scale.css'
import './world-objective.css'
import './world-navigation.css'
import './progression-landmarks.css'
import './character-continuity.css'
import './code-help.css'
import './codex.css'
import './tutorial.css'
import './inspector.css'
import './economy.css'
import './inn.css'
import './items.css'
import './item-toast.css'
import './simplify.css'
import './pause.css'
import './equipment-picker.css'
import './pause-header.css'
import './pause-icons.css'
import './pause-selector.css'
import './atlas-terrain.css'
import './atlas-exploration.css'
import './boss-guard.css'
import './pixel-art.css'
import './battle-presentation.css'
import './battle-enemies.css'
import './code-world-presentation.css'
import './battle-reading.css'
import './battle-command-hierarchy.css'
import './battle-command-menu.css'
import './battle-stable-workspace.css'

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <AppRouter />
    <AudioUnlock />
  </StrictMode>,
)
